// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjMTgzJ-jdpDoekZrCCFxaVXgldrb2OgY',
    appId: '1:489318452551:web:8a31e92964c81c13ef1062',
    messagingSenderId: '489318452551',
    projectId: 'real-estate-a9978',
    authDomain: 'real-estate-a9978.firebaseapp.com',
    storageBucket: 'real-estate-a9978.appspot.com',
    measurementId: 'G-J72B1NY8Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-7dq1tYFKf72f7jIlZnSB-YxQ2i7dKsA',
    appId: '1:489318452551:android:4fd016ca23530382ef1062',
    messagingSenderId: '489318452551',
    projectId: 'real-estate-a9978',
    storageBucket: 'real-estate-a9978.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmqtkFXwh-qRQ3AHC3EvC3Zqvio7Ehlfk',
    appId: '1:489318452551:ios:ffd309eec601e52cef1062',
    messagingSenderId: '489318452551',
    projectId: 'real-estate-a9978',
    storageBucket: 'real-estate-a9978.appspot.com',
    iosClientId: '489318452551-106uf0t5gpucqi8d3h1c4nudii7kr94d.apps.googleusercontent.com',
    iosBundleId: 'com.example.realestate',
  );
}
